# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Pi Alert' do
	pod 'Reachability', :git => 'https://github.com/tonymillion/Reachability'
	pod 'Alamofire', '~> 3.3'
	pod 'Fabric'
	pod 'Crashlytics'
end
