//
//  UIColor+AppColor.swift
//
//  Generated by Zeplin on 5/3/16.
//  Copyright (c) 2016 __MyCompanyName__. All rights reserved. 
//

import UIKit

extension UIColor {
	class func greenyBlueColor() -> UIColor {
		return UIColor(red: 82.0 / 255.0, green: 184.0 / 255.0, blue: 153.0 / 255.0, alpha: 1.0)
	}

	class func darkGreyBlueColor() -> UIColor {
		return UIColor(red: 52.0 / 255.0, green: 66.0 / 255.0, blue: 93.0 / 255.0, alpha: 1.0)
	}

	class func pineGreenColor() -> UIColor {
		return UIColor(red: 8.0 / 255.0, green: 23.0 / 255.0, blue: 36.0 / 255.0, alpha: 1.0)
	}

	class func pineGreen90Color() -> UIColor {
		return UIColor(red: 8.0 / 255.0, green: 22.0 / 255.0, blue: 36.0 / 255.0, alpha: 0.9)
	}

	class func black70Color() -> UIColor {
		return UIColor(white: 3.0 / 255.0, alpha: 0.7)
	}

	class func darkBlueGrey90Color() -> UIColor {
		return UIColor(red: 30.0 / 255.0, green: 45.0 / 255.0, blue: 75.0 / 255.0, alpha: 0.9)
	}

	class func darkGreyBlue25Color() -> UIColor {
		return UIColor(red: 52.0 / 255.0, green: 66.0 / 255.0, blue: 93.0 / 255.0, alpha: 0.25)
	}

	class func whiteThreeColor() -> UIColor {
		return UIColor(white: 255.0 / 255.0, alpha: 1.0)
	}

	class func whiteTwoColor() -> UIColor {
		return UIColor(white: 243.0 / 255.0, alpha: 1.0)
	}
}
